---
# Source: spring-boot-app-api/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deploy-stable
  labels:
    app: spring-boot-api
spec:
  selector:
    matchLabels:
      app: spring-boot-api
  replicas: 1
  strategy:
    type: RollingUpdate #Parameterize?
  template:
    metadata:
      labels:
        app: spring-boot-api
        version: stable
      annotations:
        prometheus.io/path: '/api/actuator/prometheus'
        prometheus.io/port: '8080'
        prometheus.io/scrape: 'true'
    spec:
      containers:
      - name: hello-kubernetes
        image: paulbouwer/hello-kubernetes:1.5
        ports:
        - containerPort: 8080
        env:
        - name: MESSAGE
          value: Hello I am stable